server:
  port: 8088
  servlet:
    session:
      # session will get timeout after 30 minutes
      timeout: 30m

spring:
  application:
    name: server
  jpa:
    # show sql instructions on debug console
    show-sql: true
    # auto update database table structure
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: admin
    password: B6
    url: jdbc:h2:file:/data/db
