spring:
  application:
    name: server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/steven_universe
    username: root
    password: B6
  # session 失效时间
  session:
    timeout: 86400
  jpa:
    # show sql instructions on debug console
    show-sql: true
    # auto update database table structure
    hibernate:
      ddl-auto: update
server:
  port: 8088
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值



